### ISSUE TITLE
How to use in controller tests?

### ISSUE THREAD

**Issue by ah0y** [ScoreVision/kratos_plug#2]
First off wanted to start off by saying this is an awesome library! It works great for me so far.

I just had a question on how you might test a controller that uses this plug

whenever I try to use Mox I get a 

`** (ArgumentError) module KratosPlug.KratosClient.TeslaAdapterMock is not a mock` error when trying to expect

Should I even be using Mox? Is there an easier way to get an authenticated session in a test?

**Comment by ah0y** [comment]
I figured it out:


In tests:
```elixir
   conn  |> put_req_header(KratosPlug.Defaults.header_key(), "privateToken")}
   
   Tesla.Mock.mock(KratosPlug.KratosClient.TeslaAdapterMock.mock_kratos())
```

and then in `router.ex`

```elixir
    if env != :test do
      plug KratosPlug.Plugs.KratosNativePipeline, [
        {:kratos_base_url, "your-ory-url"}
      ]
    else
      plug KratosPlug.Plugs.KratosNativePipeline,
           KratosPlug.KratosClient.TeslaAdapterMock.client_opts()
    end
```

**Comment by znorris** [comment]
@ah0y I'm happy to see you got this sorted out, and thank you for posting a solution for others.
